services:
  questdb:
    image: questdb/questdb:latest
    ports:
      - "9000:9000"
      - "8812:8812"
      - "9009:9009"
      - "9003:9003"
    networks:
      - questdbnet

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
    volumes:
      - grafana-storage:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rabbitmq:
      image: rabbitmq:4-management
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - rabbitnet

  kafka:
    image: apache/kafka-native
    ports:
      - "9092:9092"
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafkanet

  kafka-writer:
    build: ./kafka_writer
    depends_on:
      - kafka
    networks:
      - kafkanet
  
  transform:
    build: ./transform
    depends_on:
      - kafka
      - rabbitmq
    networks:
      - rabbitnet
      - kafkanet

  db-writer:
    build: ./db_writer
    depends_on:
      - rabbitmq
      - questdb
    networks:
      - rabbitnet
      - questdbnet

volumes:
  grafana-storage:

networks:
  rabbitnet: {}
  kafkanet: {}
  questdbnet: {}