services:
  questdb:
    image: questdb/questdb:latest
    ports:
      - "9000:9000"
      - "8812:8812"
      - "9009:9009"
      - "9003:9003"

  grafana:
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=250ms
    volumes:
      - grafana-storage:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rabbitmq:
      image: rabbitmq:4-management
      ports:
        - "5672:5672"
        - "15672:15672"

  kafka:
      image: apache/kafka:4.2.0
      ports:
        - "9092:9092"


volumes:
  grafana-storage: